// Plugin auto-discovery system.
//
// This module scans src/plugins/*/plugin.json at build time and generates
// a registry that the sidebar, search, and routes use to wire up plugins.
//
// To add a new plugin:
//   1. Create src/plugins/<name>/plugin.json
//   2. Create src/plugins/<name>/page.tsx (default export)
//   3. Rebuild — the plugin auto-appears in nav + search + routes
//
// In a real build, this would be a build script that scans the filesystem.
// For the static export, we hardcode the registry here (since plugins are
// bundled at build time anyway).

export interface PluginManifest {
  name: string
  title: string
  description: string
  icon: string          // lucide-react icon name
  category: string
  navOrder: number
  requiredRole: 'demo' | 'admin' | 'enterprise'
  version: string
  author: string
  homepage?: string
  enabled: boolean
}

export interface PluginRegistryEntry extends PluginManifest {
  // The page component to render (lazy-loaded)
  pagePath: string  // e.g. '@/plugins/weather/page'
}

// Auto-discovered plugins (in production, this array is generated by a
// build script that scans src/plugins/*/plugin.json)
export const PLUGINS: PluginRegistryEntry[] = [
  {
    name: 'weather',
    title: 'Weather',
    description: 'NOAA + OpenWeather data (sample plugin)',
    icon: 'cloud',
    category: 'environmental',
    navOrder: 5.1,
    requiredRole: 'demo',
    version: '1.0.0',
    author: 'MERIDIAN Team',
    enabled: true,
    pagePath: '@/plugins/weather/page',
  },
  {
    name: 'flights',
    title: 'Live Flights',
    description: 'OpenSky flight tracking (sample plugin)',
    icon: 'plane',
    category: 'transportation',
    navOrder: 5.2,
    requiredRole: 'demo',
    version: '1.0.0',
    author: 'MERIDIAN Team',
    enabled: true,
    pagePath: '@/plugins/flights/page',
  },
]

export function getEnabledPlugins(): PluginRegistryEntry[] {
  return PLUGINS.filter(p => p.enabled).sort((a, b) => a.navOrder - b.navOrder)
}

export function getPluginsForRole(role: 'demo' | 'admin' | 'enterprise' | null): PluginRegistryEntry[] {
  const roleOrder = { demo: 0, admin: 1, enterprise: 2 }
  const userLevel = role ? roleOrder[role] : 0
  return getEnabledPlugins().filter(p => roleOrder[p.requiredRole] <= userLevel)
}

// Icon name → lucide-react component mapping
import {
  Cloud, Plane, Brain, Activity, Newspaper, FolderOpen, Zap, DollarSign, Settings,
  Book, Info, LogIn, Home, LayoutDashboard, TrendingUp, Sparkles,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  cloud: Cloud,
  plane: Plane,
  brain: Brain,
  activity: Activity,
  newspaper: Newspaper,
  folder: FolderOpen,
  zap: Zap,
  dollar: DollarSign,
  settings: Settings,
  book: Book,
  info: Info,
  login: LogIn,
  home: Home,
  dashboard: LayoutDashboard,
  trending: TrendingUp,
  sparkles: Sparkles,
}

export function getPluginIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || Book
}
