// Static fallback data for GitHub Pages / static-export mode.
// Used by useFetch when API routes are unavailable (no Node.js server).

export const SYNTHETIC_FALLBACK = {
  stats: {
    counts: {
      venues: 5, symbols: 18, ticks: 12960, ohlcvBars: 4946,
      pipelines: 8, datasets: 8, mlModels: 6, predictions: 200,
      alerts: 8, activeIncidents: 0, auditLogs: 200, savedQueries: 7,
    },
    storage: {
      totalSizeBytes: 32624712000000,
      totalRows: 93868692400,
      totalSizeHuman: '29.67 TB',
      totalRowsHuman: '93.87B',
    },
    pipelines: {
      total: 8, running: 7, degraded: 1, stopped: 0,
      avgLagMs: 210.6, totalThroughputMps: 9690000,
    },
    alerts: { firing: 2, acked: 3 },
  },
  pipelines: [
    { id: 'p1', name: 'Normalize', stage: 'L3 Processing', description: 'Vendor decode -> canonical', status: 'running', parallelism: 12, throughputMps: 2100000, lagMs: 145, p99LatencyMs: 187, checkpointMs: 42, lastRestartHuman: '2h ago', incidentCount: 0 },
    { id: 'p2', name: 'Enrich', stage: 'L3 Processing', description: 'Join with reference data', status: 'running', parallelism: 24, throughputMps: 1850000, lagMs: 220, p99LatencyMs: 235, checkpointMs: 58, lastRestartHuman: '4h ago', incidentCount: 0 },
    { id: 'p3', name: 'Aggregate', stage: 'L3 Processing', description: 'OHLCV + session windows', status: 'degraded', parallelism: 48, throughputMps: 1620000, lagMs: 305, p99LatencyMs: 312, checkpointMs: 71, lastRestartHuman: '12h ago', incidentCount: 1 },
    { id: 'p4', name: 'AnomalyScore', stage: 'L3 Processing', description: 'ONNX spoofing detection', status: 'running', parallelism: 32, throughputMps: 1480000, lagMs: 198, p99LatencyMs: 218, checkpointMs: 49, lastRestartHuman: '6h ago', incidentCount: 0 },
    { id: 'p5', name: 'Iceberg Sink', stage: 'L4 Lakehouse', description: 'Exactly-once commit', status: 'running', parallelism: 16, throughputMps: 1420000, lagMs: 312, p99LatencyMs: 380, checkpointMs: 65, lastRestartHuman: '8h ago', incidentCount: 0 },
  ],
  datasets: [
    { id: 'd1', name: 'ticks.normalized', namespace: 'equities', description: 'Canonical tick stream', format: 'iceberg', rowCount: 8400000000, sizeBytes: 4120000000000, partitionKeys: 'day,symbol_bucket(64)', tier: 'hot', rowCountHuman: '8.40B', sizeHuman: '3.75 TB', queryCount: 47 },
    { id: 'd2', name: 'ticks.l2', namespace: 'equities', description: 'L2 order book deltas', format: 'iceberg', rowCount: 84000000000, sizeBytes: 28400000000000, partitionKeys: 'day,symbol_bucket(64)', tier: 'hot', rowCountHuman: '84.00B', sizeHuman: '25.84 TB', queryCount: 23 },
    { id: 'd3', name: 'ohlcv.1m', namespace: 'equities', description: '1-minute OHLCV bars', format: 'iceberg', rowCount: 24000000, sizeBytes: 1400000000, partitionKeys: 'day,symbol', tier: 'warm', rowCountHuman: '24.00M', sizeHuman: '1.30 GB', queryCount: 184 },
    { id: 'd4', name: 'alerts.spoofing', namespace: 'governance', description: 'Spoofing anomaly alerts', format: 'iceberg', rowCount: 12400, sizeBytes: 84000000, partitionKeys: 'day', tier: 'hot', rowCountHuman: '12.40K', sizeHuman: '80.11 MB', queryCount: 12 },
  ],
  slos: [
    { id: 's1', name: 'tier-1-realtime-risk', tier: 'tier-1', availabilityPct: 99.999, p99LatencyMs: 250, errorBudgetMin: 4.3, budgetConsumedPct: 38, burnRate1h: 1.2, burnRate6h: 0.8, burnRate24h: 0.6, healthStatus: 'warning' },
    { id: 's2', name: 'tier-2-posttrade', tier: 'tier-2', availabilityPct: 99.99, p99LatencyMs: 5000, errorBudgetMin: 43.2, budgetConsumedPct: 22, burnRate1h: 0.4, burnRate6h: 0.3, burnRate24h: 0.5, healthStatus: 'healthy' },
    { id: 's3', name: 'tier-3-research', tier: 'tier-3', availabilityPct: 99.9, p99LatencyMs: 60000, errorBudgetMin: 432, budgetConsumedPct: 12, burnRate1h: 0.1, burnRate6h: 0.2, burnRate24h: 0.3, healthStatus: 'healthy' },
  ],
  alerts: [
    { id: 'a1', severity: 'critical', source: 'flink', title: 'Aggregate checkpoint duration > 60s', description: 'Job Aggregate checkpoint took 78s, exceeded 60s budget', status: 'firing', tier: 'tier-1', firedAt: new Date(Date.now() - 3 * 60000).toISOString(), ageMin: 3 },
    { id: 'a2', severity: 'warning', source: 'iceberg', title: 'Manifest lock contention', description: 'Compaction held manifest tree lock for 4.2s', status: 'firing', tier: 'tier-1', firedAt: new Date(Date.now() - 8 * 60000).toISOString(), ageMin: 8 },
    { id: 'a3', severity: 'warning', source: 'kafka', title: 'Consumer lag growing', description: 'Lag rose from 12s to 18s in 5m', status: 'acked', tier: 'tier-2', ackedBy: 'sre-oncall', firedAt: new Date(Date.now() - 22 * 60000).toISOString(), ageMin: 22 },
    { id: 'a4', severity: 'info', source: 'slo', title: 'Tier-3 burn rate back to normal', description: 'Below 0.3 threshold', status: 'resolved', tier: 'tier-3', firedAt: new Date(Date.now() - 60 * 60000).toISOString(), ageMin: 60 },
  ],
  mlModels: [
    { id: 'm1', name: 'spoofing-detector', version: 'v3.4.1', type: 'classifier', framework: 'lightgbm', status: 'production', accuracy: 0.943, p99InferenceMs: 14, driftScore: 0.08, deployedAt: new Date(Date.now() - 47 * 86400000).toISOString(), predictionCount: 2847, driftStatus: 'healthy' },
    { id: 'm2', name: 'latency-arb-detector', version: 'v2.1.0', type: 'classifier', framework: 'lightgbm', status: 'production', accuracy: 0.918, p99InferenceMs: 11, driftScore: 0.14, deployedAt: new Date(Date.now() - 23 * 86400000).toISOString(), predictionCount: 1847, driftStatus: 'healthy' },
    { id: 'm3', name: 'order-imbalance-forecaster', version: 'v1.8.2', type: 'regressor', framework: 'onnx', status: 'shadow', accuracy: 0.872, p99InferenceMs: 9, driftScore: 0.21, deployedAt: new Date(Date.now() - 12 * 86400000).toISOString(), predictionCount: 945, driftStatus: 'warning' },
    { id: 'm4', name: 'volatility-regime', version: 'v0.4.0', type: 'classifier', framework: 'pytorch', status: 'shadow', accuracy: 0.803, p99InferenceMs: 22, driftScore: 0.34, deployedAt: new Date(Date.now() - 4 * 86400000).toISOString(), predictionCount: 312, driftStatus: 'critical' },
  ],
  predictions: Array.from({ length: 20 }, (_, i) => ({
    id: `pred-${i}`,
    ts: new Date(Date.now() - i * 60000).toISOString(),
    model: 'spoofing-detector v3.4.1',
    symbol: ['AAPL', 'MSFT', 'NVDA', 'TSLA'][i % 4],
    score: Math.random(),
    label: Math.random() > 0.85 ? 'spoofing' : Math.random() > 0.6 ? 'latency_arb' : 'normal',
    confidence: 0.7 + Math.random() * 0.29,
  })),
  incidents: [
    {
      id: 'inc1',
      title: 'April 2024 checkpoint storm',
      severity: 'sev1',
      status: 'resolved',
      pipelineName: 'Aggregate',
      startedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      detectedAt: new Date(Date.now() - 14 * 86400000 + 4 * 60000).toISOString(),
      resolvedAt: new Date(Date.now() - 14 * 86400000 + 18 * 60000).toISOString(),
      durationHuman: '18m',
      rootCause: 'Iceberg compaction job held manifest tree write lock during peak write throughput; Flink checkpoints abandoned after 4 retries',
      actionItems: '9 action items: dedicated compaction service, backpressure signal, pause-on-stress, alert threshold lowered, runbook updated',
    },
    {
      id: 'inc2',
      title: 'Schema registry brief outage',
      severity: 'sev3',
      status: 'resolved',
      pipelineName: null,
      startedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      detectedAt: new Date(Date.now() - 7 * 86400000 + 2 * 60000).toISOString(),
      resolvedAt: new Date(Date.now() - 7 * 86400000 + 14 * 60000).toISOString(),
      durationHuman: '14m',
      rootCause: 'Schema registry pod OOM-killed during schema validation burst',
      actionItems: 'Increase memory limit; add HPA on CPU > 70%',
    },
  ],
  lineage: {
    nodes: [
      { id: 'kafka_topic:ticks.raw.cme', type: 'kafka_topic', name: 'ticks.raw.cme' },
      { id: 'flink_job:Normalize', type: 'flink_job', name: 'Normalize' },
      { id: 'kafka_topic:ticks.normalized', type: 'kafka_topic', name: 'ticks.normalized' },
      { id: 'flink_job:Enrich', type: 'flink_job', name: 'Enrich' },
      { id: 'flink_job:Aggregate', type: 'flink_job', name: 'Aggregate' },
      { id: 'iceberg_table:ohlcv.1m', type: 'iceberg_table', name: 'ohlcv.1m' },
      { id: 'flink_job:AnomalyScore', type: 'flink_job', name: 'AnomalyScore' },
      { id: 'kafka_topic:alerts.spoofing', type: 'kafka_topic', name: 'alerts.spoofing' },
      { id: 'iceberg_table:ticks.normalized', type: 'iceberg_table', name: 'ticks.normalized' },
    ],
    edges: [
      { source: 'kafka_topic:ticks.raw.cme', target: 'flink_job:Normalize', relation: 'consumes' },
      { source: 'flink_job:Normalize', target: 'kafka_topic:ticks.normalized', relation: 'produces' },
      { source: 'kafka_topic:ticks.normalized', target: 'flink_job:Enrich', relation: 'consumes' },
      { source: 'flink_job:Enrich', target: 'flink_job:Aggregate', relation: 'transforms' },
      { source: 'flink_job:Aggregate', target: 'iceberg_table:ohlcv.1m', relation: 'produces' },
      { source: 'flink_job:Enrich', target: 'flink_job:AnomalyScore', relation: 'transforms' },
      { source: 'flink_job:AnomalyScore', target: 'kafka_topic:alerts.spoofing', relation: 'produces' },
      { source: 'kafka_topic:ticks.normalized', target: 'iceberg_table:ticks.normalized', relation: 'produces' },
    ],
  },
  audit: Array.from({ length: 30 }, (_, i) => ({
    id: `log-${i}`,
    actor: ['analyst.alice', 'sre.carol', 'ml.dave', 'service.flink', 'compliance.eve'][i % 5],
    action: ['read', 'query', 'deploy', 'write'][i % 4],
    resource: ['ticks.normalized', 'ohlcv.1m', 'alerts.spoofing', 'spoofing-detector'][i % 4],
    resourceType: ['dataset', 'model', 'pipeline'][i % 3],
    tier: ['tier-1', 'tier-2', 'tier-3'][i % 3],
    result: i % 8 === 0 ? 'deny' : 'allow',
    ts: new Date(Date.now() - i * 5 * 60000).toISOString(),
    tsHuman: new Date(Date.now() - i * 5 * 60000).toISOString(),
  })),
  queries: [
    { id: 'q1', name: 'AAPL last-hour trades', sqlText: "SELECT ts, price, size, side FROM ticks.normalized WHERE symbol = 'AAPL' AND ts > NOW() - INTERVAL '1 HOUR' ORDER BY ts DESC LIMIT 500", description: 'Recent AAPL trade ticks', createdBy: 'analyst.alice', isStarred: true, lastRunMs: 607, executionCount: 449, datasetName: 'ticks.normalized' },
    { id: 'q2', name: 'Top volume symbols today', sqlText: "SELECT symbol, SUM(volume) AS total_vol FROM ohlcv.1m WHERE ts > DATE_TRUNC('day', NOW()) GROUP BY symbol ORDER BY total_vol DESC LIMIT 20", description: 'Daily volume leaderboard', createdBy: 'analyst.bob', isStarred: true, lastRunMs: 1207, executionCount: 20, datasetName: 'ohlcv.1m' },
    { id: 'q3', name: 'Spoofing alerts last hour', sqlText: "SELECT ts, symbol, score, features FROM alerts.spoofing WHERE ts > NOW() - INTERVAL '1 HOUR' AND score > 0.85 ORDER BY score DESC", description: 'High-confidence spoofing alerts', createdBy: 'compliance.eve', isStarred: false, lastRunMs: 3170, executionCount: 337, datasetName: 'alerts.spoofing' },
    { id: 'q4', name: 'Audit denials last 24h', sqlText: "SELECT actor, action, resource, tier, ts FROM audit_log WHERE result = 'deny' AND ts > NOW() - INTERVAL '24 HOURS' ORDER BY ts DESC", description: 'Compliance denial log', createdBy: 'compliance.eve', isStarred: true, lastRunMs: 3152, executionCount: 38, datasetName: 'audit.lineage' },
  ],
}
